/*
// Inicia Si4463
*/
void SI4463_init(void)
{   
   delay_ms(35);
   
   SPIwrite(0x08, RF_GPIO_PIN_CFG_DATA);
   SPIwrite(0x05, RF_GLOBAL_XO_TUNE_1_DATA);
   SPIwrite(0x05, RF_GLOBAL_CONFIG_1_DATA);
   SPIwrite(0x06, RF_INT_CTL_ENABLE_2_DATA);
   SPIwrite(0x08, RF_FRR_CTL_A_MODE_4_DATA);
   SPIwrite(0x0D, RF_PREAMBLE_TX_LENGTH_9_DATA);
   SPIwrite(0x09, RF_SYNC_CONFIG_5_DATA);
   SPIwrite(0x05, RF_PKT_CRC_CONFIG_7_DATA);
   SPIwrite(0x10, RF_PKT_LEN_12_DATA);
   SPIwrite(0x10, RF_PKT_FIELD_1_LENGTH_12_8_12_DATA);
   SPIwrite(0x0C, RF_PKT_FIELD_4_LENGTH_12_8_8_DATA);
   SPIwrite(0x10, RF_MODEM_MOD_TYPE_12_DATA);
   SPIwrite(0x05, RF_MODEM_FREQ_DEV_0_1_DATA);
   SPIwrite(0x0C, RF_MODEM_TX_RAMP_DELAY_8_DATA);
   SPIwrite(0x0D, RF_MODEM_BCR_OSR_1_9_DATA);
   SPIwrite(0x0B, RF_MODEM_AFC_GEAR_7_DATA);         
   SPIwrite(0x05, RF_MODEM_AGC_CONTROL_1_DATA);
   SPIwrite(0x0D, RF_MODEM_AGC_WINDOW_SIZE_9_DATA);
   SPIwrite(0x0F, RF_MODEM_OOK_CNT1_11_DATA);
   SPIwrite(0x05, RF_MODEM_RSSI_COMP_1_DATA);
   SPIwrite(0x05, RF_MODEM_CLKGEN_BAND_1_data);
   SPIwrite(0x10, RF_MODEM_CHFLT_RX1_CHFLT_COE13_7_0_12_DATA);
   SPIwrite(0x10, RF_MODEM_CHFLT_RX1_CHFLT_COE1_7_0_12_DATA); 
   SPIwrite(0x10, RF_MODEM_CHFLT_RX2_CHFLT_COE7_7_0_12_DATA);       
   SPIwrite(0x08, RF_PA_MODE_4_DATA);
   SPIwrite(0x0B, RF_SYNTH_PFDCP_CPFF_7_DATA);
   SPIwrite(0x10, RF_MATCH_VALUE_1_12_DATA); 
   SPIwrite(0x0C, RF_FREQ_CONTROL_INTE_8_DATA);

} 
